### ISSUE TITLE
Is there a configuration to setup a timeout for a SMTP connection?

### ISSUE THREAD

**Issue by nfinelli-cmovil** [acmailer/acmailer#252]
Hi,

We've implemented the library with SMTP.  Sometimes our smtp provider hangs until various seconds and the library return as a "stream_socket_client(): unable to connect (connection timeout)"  is possible to add a highest timeout?

Regards

**Comment by acelaya** [comment]
I have just checked, and laminas-mail doesn't seem to allow changing the timeout for SMTP connections.

However, maybe you can try playing with this option: `ini_set("default_socket_timeout", 10)`.

The value there is set in seconds, and in theory, it should affect any socket connection opened after you set that.

**Comment by nfinelli-cmovil** [comment]
Thanks I'll try with this option!

**Comment by nfinelli-cmovil** [comment]
Is possible to add a "connection_time_limit" ?  In docs I can see this config but if I try to add this on my code I get:

Zend\Stdlib\Exception\BadMethodCallException
 The option "connection_time_limit" does not have a callable "setConnectionTimeLimit" ("setconnectiontimelimit")

Thanks for your help!

**Comment by acelaya** [comment]
You should be able to use that, yes. However, that option was added in laminas-mail v2.10, and you are probably using an older version. That's why you get that error.

In any case, the purpose of that option does not seem to be handling timeouts on too slow servers/connections, but to enforce connections to be reopened/recreated after certain amount of time, to avoid problems with expiring connections in long-running process.

But of course, you can try to update to laminas-mail 2.10 and see if it helps.

**Comment by nfinelli-cmovil** [comment]
Thanks!
